"""
Vision service — OPTIONAL AI verifier using the Kimi K2.5 vision model.

This is NOT the core compliance engine. The local OCR + Rule Engine handles
all compliance checks independently. The AI verifier only acts as a
second-pass to catch things the rule engine might have missed.

Can be completely disabled via config (ai_enabled=False) or per-request
(skip_ai=True).
"""

import base64
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional

from app.config import settings

logger = logging.getLogger(__name__)

# System prompt that instructs the vision model how to act as an evaluator
EVALUATOR_SYSTEM_PROMPT = """You are an expert Legal Metrology compliance AI Evaluator.
A local OCR rule engine has already scanned the product images and generated an Initial Compliance Report.

You will be provided with:
1. The raw text extracted by the local OCR.
2. The Initial Report generated by the Python rule engine.
3. The original images.

Review the images carefully. 
- If the Rule Engine gave a "fail" or "warning", but you clearly see the required information or determine it is compliant, you should override it to "pass".
- Specifically evaluate visual rules like Font Size, Principal Display Panel, and language requirements. 
- For Allergen info and Veg/Non-Veg symbols: if you visually identify the Green/Brown dot, pass the Veg/Non-Veg rule.

Return ONLY a valid JSON object containing a single key "pass_rules" with a list of the `rule_id`s that should be overridden to "pass". 
Example:
{
  "pass_rules": ["VEG_1", "R8_PDP", "ALLRG_1"]
}
Do not include markdown blocks, backticks, or any conversational text.
"""


def is_ai_available() -> bool:
    """Check if AI evaluation is available and enabled."""
    if not settings.ai_enabled:
        return False
    if settings.aicredits_api_key in ("YOUR_API_KEY", "", None):
        return False
    return True


def _encode_image(image_path: str) -> str:
    """Read an image file, resize if too large, and return its base64-encoded JPEG string."""
    from PIL import Image
    import io
    
    with Image.open(image_path) as img:
        # Convert to RGB to ensure compatibility with JPEG format
        if img.mode in ("RGBA", "P", "LA", "L"):
            img = img.convert("RGB")
            
        # Resize if max dimension exceeds 1024 to save payload size
        max_dim = 1024
        if max(img.width, img.height) > max_dim:
            ratio = max_dim / max(img.width, img.height)
            new_size = (int(img.width * ratio), int(img.height * ratio))
            img = img.resize(new_size, Image.Resampling.LANCZOS)
            
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=85)
        return base64.b64encode(buffer.getvalue()).decode("utf-8")

def _get_mime_type(filename: str) -> str:
    """Determine MIME type from file extension."""
    ext = Path(filename).suffix.lower()
    mime_map = {
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
        ".webp": "image/webp",
        ".gif": "image/gif",
        ".bmp": "image/bmp",
    }
    return mime_map.get(ext, "image/jpeg")

async def evaluate_with_ai(image_paths: List[str], raw_text: str, initial_report: List[Dict]) -> List[Dict]:
    """
    Send the initial report and images to the AI to verify and correct
    any mistakes made by the local OCR/Regex engine.

    If AI is not available, returns the initial report unchanged.
    """
    if not is_ai_available():
        logger.info("AI evaluation skipped: AI is not available or disabled.")
        return initial_report

    try:
        import openai
    except ImportError:
        logger.warning("OpenAI package not installed. AI evaluation skipped.")
        return initial_report

    client = openai.OpenAI(
        base_url=settings.aicredits_base_url,
        api_key=settings.aicredits_api_key,
    )

    content: list = [
        {
            "type": "text",
            "text": (
                "Please evaluate the following Initial Compliance Report generated by our local OCR Rule Engine.\n\n"
                f"--- RAW OCR TEXT ---\n{raw_text}\n\n"
                f"--- INITIAL REPORT ---\n{json.dumps(initial_report, indent=2)}\n\n"
                "Review the images. If the rule engine missed something, fix it. Return the final corrected JSON array."
            ),
        }
    ]

    for img_path in image_paths:
        try:
            b64 = _encode_image(img_path)
            content.append({
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
            })
        except Exception as e:
            logger.warning(f"Could not encode image {img_path}: {e}")

    if len(content) < 2:
        logger.error("No images could be loaded for evaluation.")
        return initial_report

    try:
        response = client.chat.completions.create(
            model=settings.vision_model,
            messages=[
                {"role": "system", "content": EVALUATOR_SYSTEM_PROMPT},
                {"role": "user", "content": content},
            ],
            max_tokens=4096,
            temperature=0.1,
            response_format={"type": "json_object"},
        )

        raw_content = response.choices[0].message.content
        if not raw_content:
            return initial_report

        raw_content = raw_content.strip()

        # Clean JSON block
        if "```json" in raw_content:
            raw_content = raw_content.split("```json")[1].split("```")[0].strip()
        elif "```" in raw_content:
            raw_content = raw_content.split("```")[1].strip()
            if raw_content.startswith("json"):
                raw_content = raw_content[4:].strip()
                
        # Fallback block extraction
        start_idx = raw_content.find('{')
        end_idx = raw_content.rfind('}')
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            raw_content = raw_content[start_idx:end_idx+1]

        parsed = json.loads(raw_content)
        
        # Apply overrides
        pass_rules = parsed.get("pass_rules", [])
        if not isinstance(pass_rules, list):
            pass_rules = []
            
        for rule in initial_report:
            if rule["rule_id"] in pass_rules:
                rule["status"] = "pass"
                rule["details"] = "Verified compliant by AI Vision Evaluator."
                
        return initial_report

    except Exception as e:
        logger.error(f"AI Evaluation failed: {e}")
        logger.error(f"RAW CONTENT WAS:\n{raw_content if 'raw_content' in locals() else 'None'}")
        return initial_report
